# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use a version consistent with requirements.txt if possible
    hooks:
      - id: black
        args: ["backend/"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use a version consistent with requirements.txt if possible
    hooks:
      - id: isort
        args: ["backend/"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Use a version consistent with requirements.txt if possible
    hooks:
      - id: flake8
        args: ["backend/"]
        # Optionally add --ignore or --exclude if needed
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1 # Use a version consistent with requirements.txt if possible
    hooks:
      - id: mypy
        args: ["backend/"]
        additional_dependencies: []
# Add any necessary mypy plugins or stubs here, e.g.:
# types-requests,
# types-redis,
# sqlalchemy-stubs # Already in requirements.txt
