include:
  - path: ./backend/docker-compose.yml
  - path: ./react-frontend/docker-compose.yml

services:
  # Mail testing service for development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025" # Web UI
    restart: unless-stopped
    networks:
      - fastapi_rbac_network

  # PostgreSQL Database (only used for Docker environments)
  fastapi_rbac_db:
    image: bitnami/postgresql
    restart: always
    container_name: fastapi_rbac_db
    ports:
      - "5453:5432" # Remove this on production
    env_file:
      - ./backend/.env.test
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER:-postgres}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRESQL_DATABASE=${DATABASE_NAME:-fastapi_db}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - ALLOW_EMPTY_PASSWORD=yes
    user: root
    volumes:
      - .database:/bitnami/postgresql
      - ./scripts/database/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    expose:
      - 5432
    networks:
      - fastapi_rbac_network

  fastapi_rbac_pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_rbac_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - fastapi_rbac_network

  fastapi_rbac_redis_server:
    image: redis:alpine
    container_name: fastapi_rbac_redis_server
    restart: always
    ports:
      - "6379:6379" # Publish Redis port to host machine
    expose:
      - 6379
    networks:
      - fastapi_rbac_network

volumes:
  .database:
  pgadmin-data:

networks:
  fastapi_rbac_network:
    name: fastapi_rbac_network
    external: true
