# Docker Compose for Production Testing Environment
# This configuration simulates production environment for testing purposes
# Uses production-like settings but with testing-specific configurations

include:
  - path: ./backend/docker-compose.prod.yml
  - path: ./react-frontend/docker-compose.prod.yml

services:
  # Mail testing service for production testing
  mailhog_prod_test:
    image: mailhog/mailhog:latest
    container_name: fastapi_rbac_mailhog_prod_test
    ports:
      - "1026:1025" # Different port to avoid conflicts with dev
      - "8026:8025" # Web UI on different port
    restart: unless-stopped
    networks:
      - fastapi_rbac_prod_test_network

  # Database service for production testing
  fastapi_rbac_db_prod_test:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_db
    container_name: fastapi_rbac_db_prod_test
    ports:
      - "5434:5432" # Different port for prod test
    volumes:
      - fastapi_rbac_db_prod_test_data:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - fastapi_rbac_prod_test_network
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-fastapi_prod_test_db}

  # Redis service for production testing
  fastapi_rbac_redis_prod_test:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_redis
    container_name: fastapi_rbac_redis_prod_test
    ports:
      - "6380:6379" # Different port for prod test
    volumes:
      - fastapi_rbac_redis_prod_test_data:/data
    networks:
      - fastapi_rbac_prod_test_network

  # Backend API service for production testing
  fastapi_rbac_prod_test:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac
    container_name: fastapi_rbac_prod_test
    image: fastapi_rbac:prod-test
    environment:
      - MODE=production
      - DATABASE_HOST=fastapi_rbac_db_prod_test
      - REDIS_HOST=fastapi_rbac_redis_prod_test
      - SMTP_HOST=mailhog_prod_test
    depends_on:
      fastapi_rbac_db_prod_test:
        condition: service_healthy
      fastapi_rbac_redis_prod_test:
        condition: service_healthy
    ports:
      - "8001:8000" # Different port for prod test
    networks:
      - fastapi_rbac_prod_test_network

  # Celery worker service for production testing
  fastapi_rbac_worker_prod_test:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_worker
    container_name: fastapi_rbac_worker_prod_test
    image: fastapi_rbac_worker:prod-test
    environment:
      - MODE=production
      - DATABASE_HOST=fastapi_rbac_db_prod_test
      - REDIS_HOST=fastapi_rbac_redis_prod_test
    depends_on:
      fastapi_rbac_db_prod_test:
        condition: service_healthy
      fastapi_rbac_redis_prod_test:
        condition: service_healthy
    networks:
      - fastapi_rbac_prod_test_network

  # Celery beat service for production testing
  fastapi_rbac_beat_prod_test:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_beat
    container_name: fastapi_rbac_beat_prod_test
    image: fastapi_rbac_worker:prod-test
    environment:
      - MODE=production
      - DATABASE_HOST=fastapi_rbac_db_prod_test
      - REDIS_HOST=fastapi_rbac_redis_prod_test
    depends_on:
      fastapi_rbac_db_prod_test:
        condition: service_healthy
      fastapi_rbac_redis_prod_test:
        condition: service_healthy
      fastapi_rbac_worker_prod_test:
        condition: service_started
    volumes:
      - fastapi_rbac_celery_beat_prod_test_data:/app/celerybeat-schedule
    networks:
      - fastapi_rbac_prod_test_network

  # PgAdmin for production testing
  fastapi_rbac_pgadmin_prod_test:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_pgadmin
    container_name: fastapi_rbac_pgadmin_prod_test
    ports:
      - "8081:80" # Different port for prod test
    volumes:
      - fastapi_rbac_pgadmin_prod_test_data:/var/lib/pgadmin
    depends_on:
      fastapi_rbac_db_prod_test:
        condition: service_healthy
    networks:
      - fastapi_rbac_prod_test_network

  # Frontend service for production testing
  react_frontend_prod_test:
    extends:
      file: ./react-frontend/docker-compose.prod.yml
      service: react_frontend
    container_name: react_frontend_prod_test
    image: react_frontend:prod-test
    environment:
      - VITE_API_BASE_URL=http://localhost:8001/api/v1 # Point to prod test backend
    depends_on:
      - fastapi_rbac_prod_test
    ports:
      - "81:80" # Different port for prod test
    networks:
      - fastapi_rbac_prod_test_network

volumes:
  fastapi_rbac_db_prod_test_data:
    name: fastapi_rbac_db_prod_test_data
  fastapi_rbac_redis_prod_test_data:
    name: fastapi_rbac_redis_prod_test_data
  fastapi_rbac_pgadmin_prod_test_data:
    name: fastapi_rbac_pgadmin_prod_test_data
  fastapi_rbac_celery_beat_prod_test_data:
    name: fastapi_rbac_celery_beat_prod_test_data

networks:
  fastapi_rbac_prod_test_network:
    name: fastapi_rbac_prod_test_network
    driver: bridge
