services:
  fastapi_rbac:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fastapi_rbac:latest
    container_name: fastapi_rbac
    env_file:
      - ./backend/backend.env
    environment:
      - FASTAPI_ENV=${FASTAPI_ENV}
    ports:
      - "8000:8000"
    volumes:
      - backend:/app
    networks:
      - fastapi_rbac_network
    depends_on:
      - fastapi_rbac_db
      - mailhog
      - fastapi_rbac_redis_server

  # react_frontend:
  #   build:
  #     context: ./react-frontend
  #     dockerfile: Dockerfile
  #   image: react_frontend:latest
  #   container_name: react_frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - fastapi_rbac
  #   networks:
  #     - fastapi_rbac_network

  # Mail testing service for development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025" # Web UI
    restart: unless-stopped
    networks:
      - fastapi_rbac_network

  # fastapi_rbac_frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   image: fastapi_rbac_frontend:latest
  #   container_name: fastapi_rbac_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/frontend
  #   networks:
  #     - fastapi_rbac_network

  #  fastapi_rbac_queue:
  #    build:
  #      context: ./
  #      dockerfile: queue.dockerfile
  #    image: fastapi_rbac_queue:latest
  #    container_name: fastapi_rbac_queue
  #    volumes:
  #      - .:/app
  #    depends_on:
  #      - fastapi_rbac
  #    networks:
  #      - fastapi_rbac_network

  fastapi_rbac_db:
    image: bitnami/postgresql
    restart: always
    container_name: fastapi_rbac_db
    ports:
      - "5453:5432" # Remove this on production
    env_file:
      - ./backend/backend.env
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
    user: root
    volumes:
      - .database:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    expose:
      - 5432
    networks:
      - fastapi_rbac_network

  fastapi_rbac_pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_rbac_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - fastapi_rbac_network

  fastapi_rbac_redis_server:
    image: redis:alpine
    container_name: fastapi_rbac_redis_server
    restart: always
    expose:
      - 6379
    env_file:
      - "./backend/backend.env"
    networks:
      - fastapi_rbac_network

volumes:
  .database:
  pgadmin-data:
  backend:

networks:
  fastapi_rbac_network:
    driver: bridge
