services:
  # Database service
  fastapi_rbac_db:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_db

  # Redis service
  fastapi_rbac_redis:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_redis

  # Backend API service
  fastapi_rbac:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac
    depends_on:
      - fastapi_rbac_db
      - fastapi_rbac_redis
    ports:
      - "8000:8000"

  # Celery worker service
  fastapi_rbac_worker:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_worker
    depends_on:
      - fastapi_rbac_db
      - fastapi_rbac_redis

  # Celery beat service
  fastapi_rbac_beat:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_beat
    depends_on:
      - fastapi_rbac_db
      - fastapi_rbac_redis
      - fastapi_rbac_worker

  fastapi_rbac_pgadmin:
    extends:
      file: ./backend/docker-compose.prod.yml
      service: fastapi_rbac_pgadmin
    depends_on:
      fastapi_rbac_db:
        condition: service_healthy
  # Frontend service
  react_frontend:
    extends:
      file: ./react-frontend/docker-compose.prod.yml
      service: react_frontend
    environment:
      - VITE_API_BASE_URL=/api/v1 # Use relative path, nginx will proxy to backend
    depends_on:
      - fastapi_rbac
    ports:
      - "80:80"

networks:
  fastapi_rbac_network:
    name: fastapi_rbac_network
    driver: bridge

volumes:
  postgres_data:
  celery_beat_data:
  redis_data:
  pgadmin_data:
