"""add created_by_id instead of inserted_by

Revision ID: 8c263ccc446a
Revises: c93f54e30e5c
Create Date: 2024-04-25 22:13:36.062988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c263ccc446a'
down_revision: Union[str, None] = 'c93f54e30e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Permission', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'Permission', 'User', ['created_by_id'], ['id'])
    op.drop_column('Permission', 'inserted_by')
    op.add_column('PermissionGroup', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'PermissionGroup', 'User', ['created_by_id'], ['id'])
    op.drop_column('PermissionGroup', 'inserted_by')
    op.add_column('Role', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'Role', 'User', ['created_by_id'], ['id'])
    op.drop_column('Role', 'inserted_by')
    op.add_column('RoleGroup', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'RoleGroup', 'User', ['created_by_id'], ['id'])
    op.drop_column('RoleGroup', 'inserted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoleGroup', sa.Column('inserted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'RoleGroup', type_='foreignkey')
    op.drop_column('RoleGroup', 'created_by_id')
    op.add_column('Role', sa.Column('inserted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Role', type_='foreignkey')
    op.drop_column('Role', 'created_by_id')
    op.add_column('PermissionGroup', sa.Column('inserted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'PermissionGroup', type_='foreignkey')
    op.drop_column('PermissionGroup', 'created_by_id')
    op.add_column('Permission', sa.Column('inserted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Permission', type_='foreignkey')
    op.drop_column('Permission', 'created_by_id')
    # ### end Alembic commands ###
