"""new 2

Revision ID: c93f54e30e5c
Revises: 0c11825e2e0c
Create Date: 2024-04-24 15:23:57.850036

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c93f54e30e5c"
down_revision: Union[str, None] = "0c11825e2e0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_PermissionGroup_permission_group_id"),
        "PermissionGroup",
        ["permission_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_PermissionGroup_permission_group_id"), table_name="PermissionGroup")
    # ### end Alembic commands ###
