# React Frontend Testing Docker Compose
# Used for testing and CI/CD pipelines

services:
  react_frontend_test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=testing
    image: react_frontend:test
    container_name: react_frontend_test
    environment:
      - NODE_ENV=testing
      - VITE_API_BASE_URL=http://fastapi_rbac_test:8002/api/v1
    env_file:
      - .env.test
    ports:
      - '3001:80' # Different port for testing
    networks:
      - fastapi_rbac_test_network
    depends_on:
      - fastapi_rbac_test

networks:
  fastapi_rbac_test_network:
    name: fastapi_rbac_test_network
    external: true
