# React Frontend Production Docker Compose
# Modular, directory-scoped, and environment-variable driven

services:
  react_frontend:
    build:
      context: ${REACT_FRONTEND_SRC:-.}
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    image: react_frontend:prod
    container_name: react_frontend_prod
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api/v1}
    env_file:
      - .env.production
    ports:
      - '${REACT_FRONTEND_PORT:-80}:80'
    restart: always
    networks:
      - fastapi_rbac_prod_network
    # Add volume for logs or static if needed
    # volumes:
    #   - ${REACT_FRONTEND_LOGS:-./logs}:/app/logs
    #   - ${REACT_FRONTEND_STATIC:-./static}:/app/static
    depends_on: []

networks:
  fastapi_rbac_prod_network:
    name: fastapi_rbac_prod_network
    driver: bridge
    external: true
