name: Backend Security Scan

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-security.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-security.yml"
  schedule:
    - cron: "0 0 * * 0" # Weekly scan on Sundays

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      - name: Scan dependencies with Safety
        run: |
          cd backend
          safety scan -r requirements.txt

      - name: Scan code with Bandit
        run: |
          cd backend
          bandit -r app -f json -o bandit-results.json || true

      - name: Upload Bandit scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: backend/bandit-results.json
          retention-days: 7

  docker-scan:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    needs: [security-scan]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: fastapi-rbac-backend:latest
          outputs: type=docker,dest=/tmp/fastapi-rbac-backend.tar

      - name: Load image
        run: docker load --input /tmp/fastapi-rbac-backend.tar

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fastapi-rbac-backend:latest
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
          category: trivy
